<?php

return [

    //// Webthe
    'telco' => 'VIETTEL, VINAPHONE, MOBIFONE, VCOIN, GARENA, ZING, GATE, KPLUS',
    'charging' => 'VIETTEL, VIETTELAUTO, VINAPHONE, VINAPHONEAUTO, MOBIFONE, MOBIFONEAUTO, VCOIN, GARENA, ZING, GATE',
    'mtopup' => 'VIETTEL_TRATRUOC,VIETTEL_TRASAU, VINAPHONE_TRATRUOC, VINAPHONE_TRASAU, MOBIFONE_TRATRUOC, MOBIFONE_TRASAU, VIETTEL_INTERNET, KPLUS, MYVIETTEL, MYVINAPHONE, GARENA',




];